// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFLRookieGuide.Context;

#nullable disable

namespace NFLRookieGuide.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241207233125_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Play", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position10Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position4Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position5Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position6Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position7Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position8Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position9Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Position10Id");

                    b.HasIndex("Position1Id");

                    b.HasIndex("Position2Id");

                    b.HasIndex("Position3Id");

                    b.HasIndex("Position4Id");

                    b.HasIndex("Position5Id");

                    b.HasIndex("Position6Id");

                    b.HasIndex("Position7Id");

                    b.HasIndex("Position8Id");

                    b.HasIndex("Position9Id");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.PlayerAPI", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RosterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("birth_date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("birth_place")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("college")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("high_school")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("jersey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rookie_year")
                        .HasColumnType("INTEGER");

                    b.Property<float>("weight")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("RosterId");

                    b.ToTable("PlayerAPI");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date_created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPlayers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.RosterPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RosterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedSlots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RosterId");

                    b.ToTable("RosterPlays");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.RosterPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RosterId");

                    b.ToTable("RosterPlayer");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_founded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLRookieGuide.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Play", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.Position", "Position10")
                        .WithMany()
                        .HasForeignKey("Position10Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position1")
                        .WithMany()
                        .HasForeignKey("Position1Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position2")
                        .WithMany()
                        .HasForeignKey("Position2Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position3")
                        .WithMany()
                        .HasForeignKey("Position3Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position4")
                        .WithMany()
                        .HasForeignKey("Position4Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position5")
                        .WithMany()
                        .HasForeignKey("Position5Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position6")
                        .WithMany()
                        .HasForeignKey("Position6Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position7")
                        .WithMany()
                        .HasForeignKey("Position7Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position8")
                        .WithMany()
                        .HasForeignKey("Position8Id");

                    b.HasOne("NFLRookieGuide.Model.Position", "Position9")
                        .WithMany()
                        .HasForeignKey("Position9Id");

                    b.Navigation("Position1");

                    b.Navigation("Position10");

                    b.Navigation("Position2");

                    b.Navigation("Position3");

                    b.Navigation("Position4");

                    b.Navigation("Position5");

                    b.Navigation("Position6");

                    b.Navigation("Position7");

                    b.Navigation("Position8");

                    b.Navigation("Position9");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Player", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLRookieGuide.Model.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.PlayerAPI", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.Roster", null)
                        .WithMany("PlayerAPI")
                        .HasForeignKey("RosterId");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Roster", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.User", "user")
                        .WithMany("Rosters")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.RosterPlay", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.Roster", null)
                        .WithMany("RosterPlays")
                        .HasForeignKey("RosterId");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.RosterPlayer", b =>
                {
                    b.HasOne("NFLRookieGuide.Model.Player", "Player")
                        .WithMany("RosterPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLRookieGuide.Model.Roster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Player", b =>
                {
                    b.Navigation("RosterPlayers");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Roster", b =>
                {
                    b.Navigation("PlayerAPI");

                    b.Navigation("RosterPlays");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("NFLRookieGuide.Model.User", b =>
                {
                    b.Navigation("Rosters");
                });
#pragma warning restore 612, 618
        }
    }
}
